In [1]:
import pandas as pd
import numpy as np

In [2]:
# import training data
dft_eng = pd.read_csv('../data/dft_eng.csv')
dft_jap = pd.read_csv('../data/dft_jap.csv')
dft_fin = pd.read_csv('../data/dft_fin.csv')

# import validation data
dfv_eng = pd.read_csv('../data/dfv_eng.csv')
dfv_jap = pd.read_csv('../data/dfv_jap.csv')
dfv_fin = pd.read_csv('../data/dfv_fin.csv')

#import word count
word_count = pd.read_csv('../data/question_word_count.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../data/dft_eng.csv'

In [3]:
stop_words = ['\n',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'did',
 'do',
 'does',
 'doing',
 'don',
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'has',
 'have',
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'me',
 'more',
 'most',
 'my',
 'myself',
 'no',
 'nor',
 'not',
 'now',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 's',
 'same',
 'she',
 'should',
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 'very',
 'was',
 'we',
 'were',
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'you',
 'your',
 'yours',
 'yourself',
 'yourselves',
 '{',
 '|',
 '}',
 '~']

In [5]:
def ans_freq(que, doc):

    freq = [x for x in que if x in doc]
    freq = len(freq)/len(que)
    return freq

In [6]:
def freq_words_in_text (df_t,df_v):
    for df in [df_t,df_v]:
        frequency = []
        for question, answer in zip(df['question_text_tokenized'], df['document_plaintext_tokenized']):
            frequency.append(ans_freq(eval(question), eval(answer)))

        df['word_frequency_score'] = frequency

In [ ]:
dft_eng.to_csv('dft_eng_word_freq.csv',index=False) 
dfv_eng.to_csv('dfv_eng_word_freq.csv',index=False) 

In [8]:
def get_highest_wordscore(que, language, data):
    count = word_count.loc[(word_count['word'].isin(eval(que)))&(word_count['language']==language)]
    return count.iloc[np.argmax(count['norm'])]['norm']
     

get_highest_wordscore(dft_eng.question_text_tokenized[0],dft_eng.language[0], word_count)

0.9996961121346224

In [10]:
for df in [dft_jap,dfv_jap,dft_eng,dfv_eng,dft_fin,dfv_fin]:
    highest_wordscore = []
    for que,language in zip(df['question_text_tokenized'], df['language']):
        count = word_count.loc[(word_count['word'].isin(eval(que)))&(word_count['language']==language)]
        highest_wordscore.append(count.iloc[np.argmax(count['norm'])]['norm'])

    df['highest_wordscore'] = highest_wordscore
    

KeyboardInterrupt: 

In [ ]:
highest_wordscore = []
for question, document in zip(dfv_eng.question_text_tokenized.values,dfv_eng.document_plaintext_tokenized.values):
    if eval(question)[-2] in eval(document):
        highest_wordscore.append(1)
    else:
        highest_wordscore.append(0)

In [ ]:
for question, document in zip(dft_eng.question_text_tokenized.values[-100:],dft_eng.document_plaintext_tokenized.values[-100:]):
    if eval(question)[-2] in eval(document):
        highest_wordscore.append(word_count.loc[(word_count['word']==eval(question)[-2])&(word_count['language']=='english')].norm.values[0])
    else:
        highest_wordscore.append(0)

In [ ]:
temp = dft_eng[:100]

In [ ]:
temp = temp.append(dft_eng[-100:])

In [ ]:
dft_eng(highest_wordscore)

In [ ]:
dfv_eng['highest_wordscore'] = highest_wordscore

In [ ]:
dfv_eng[['word_frequency_score','highest_wordscore','labels']]

In [ ]:
plt.scatter(dft_eng.word_frequency_score[:3696], dft_eng.highest_wordscore[:3696], c ="blue")
plt.scatter(dft_eng.word_frequency_score[-3693:], dft_eng.highest_wordscore[-3693:], c ="red")
plt.show()

In [ ]:
dft_eng.loc[dft_eng['labels']==0]

In [ ]:
len(dft_eng.loc[(dft_eng['highest_wordscore']!=0)&((dft_eng['labels']==1))])/3696

In [ ]:
len(dft_eng.loc[(dft_eng['highest_wordscore']==0)&((dft_eng['labels']==0))])/3693

In [ ]:
len(dft_eng.loc[(dft_eng['highest_wordscore']==0)])

In [ ]:
len(dft_eng)

In [ ]:
clf = LogisticRegression(random_state=0).fit(dft_eng[['word_frequency_score','highest_wordscore']].to_numpy(),dft_eng.labels.values)
pred = clf.predict(dfv_eng[['word_frequency_score','highest_wordscore']].to_numpy())
accuracy_score(pred, dfv_eng.labels.values)

In [ ]:
dfv_eng

In [ ]:
dft_eng.question_text_tokenized

In [ ]:
dft_eng.word_frequency_score.values.reshape(-1, 1)

In [ ]:
dft_eng[['word_frequency_score','highest_wordscore']].to_numpy()

In [ ]:
eval(dft_eng.question_text_tokenized.values[0])

In [ ]:
eng_word_count = word_count.loc[word_count['language']=='english']

In [ ]:
eng_word_count.loc[eng_word_count['word'].isin(eval(dft_eng.question_text_tokenized.values[0]))]

In [ ]:
eng_word_count.loc[eng_word_count['word'].isin(eval(dft_eng.document_plaintext_tokenized.values[0]))]

## Bag of Words

In [16]:
bag_df = dft_eng[["question_text_tokenized", "document_plaintext_tokenized", "labels"]]

bag_df

question_text_tokenized  \
0     ['when', 'was', 'quantum', 'field', 'theory', ...   
1     ['who', 'was', 'the', 'first', 'nobel', 'prize...   
2     ['when', 'is', 'the', 'dialectical', 'method',...   
3                    ['who', 'invented', 'hangul', '?']   
4            ['what', 'do', 'grasshoppers', 'eat', '?']   
...                                                 ...   
7384  ['what', 'was', 'neil', 'brooks', "'", 'fastes...   
7385  ['who', 'are', 'the', 'three', 'most', 'import...   
7386  ['who', 'was', 'costume', 'designer', 'for', '...   
7387  ['who', 'developed', 'the', 'first', 'thermonu...   
7388  ['what', 'is', 'the', 'population', 'of', 'mah...   

                           document_plaintext_tokenized  labels  
0     ['quantum', 'field', 'theory', 'naturally', 'b...       1  
1     ['the', 'nobel', 'prize', 'in', 'literature', ...       1  
2     ['dialectic', 'or', 'dialectics', '(', 'greek'...       1  
3     ['hangul', 'was', 'personally', 'created', 'an...       1  
4     ['grasshoppers', 'are', 'plant-eaters', ',', '...       1  
...                                                 ...     ...  
7384  ['the', 'medley', 'relay', 'was', 'scheduled',...       0  
7385  ['sāmkhya', 'is', 'a', 'dualist', 'philosophic...       0  
7386  ['mollo', 'was', 'surprised', 'by', 'the', 'su...       0  
7387  ['in', 'the', 'end', ',', 'president', 'truman...       0  
7388  ['the', 'previous', 'mayor', ',', 'bill', 'laf...       0  

[7389 rows x 3 columns]

In [40]:
data = dft_eng[["document_plaintext_tokenized", "labels"]]
test_data = dft_eng[["question_text_tokenized", "labels"]]

In [41]:
data.to_numpy()

array([["['quantum', 'field', 'theory', 'naturally', 'began', 'with', 'the', 'study', 'of', 'electromagnetic', 'interactions', ',', 'as', 'the', 'electromagnetic', 'field', 'was', 'the', 'only', 'known', 'classical', 'field', 'as', 'of', 'the', '1920s.', '[', '8', ']', ':1']",
        1],
       ['[\'the\', \'nobel\', \'prize\', \'in\', \'literature\', \'(\', \'swedish\', \':\', \'nobelpriset\', \'i\', \'litteratur\', \')\', \'is\', \'awarded\', \'annually\', \'by\', \'the\', \'swedish\', \'academy\', \'to\', \'authors\', \'for\', \'outstanding\', \'contributions\', \'in\', \'the\', \'field\', \'of\', \'literature.\', \'it\', \'is\', \'one\', \'of\', \'the\', \'five\', \'nobel\', \'prizes\', \'established\', \'by\', \'the\', \'1895\', \'will\', \'of\', \'alfred\', \'nobel\', \',\', \'which\', \'are\', \'awarded\', \'for\', \'outstanding\', \'contributions\', \'in\', \'chemistry\', \',\', \'physics\', \',\', \'literature\', \',\', \'peace\', \',\', \'and\', \'physiology\', \'or\', \'med

In [45]:
data

document_plaintext_tokenized  labels
0     ['quantum', 'field', 'theory', 'naturally', 'b...       1
1     ['the', 'nobel', 'prize', 'in', 'literature', ...       1
2     ['dialectic', 'or', 'dialectics', '(', 'greek'...       1
3     ['hangul', 'was', 'personally', 'created', 'an...       1
4     ['grasshoppers', 'are', 'plant-eaters', ',', '...       1
...                                                 ...     ...
7384  ['the', 'medley', 'relay', 'was', 'scheduled',...       0
7385  ['sāmkhya', 'is', 'a', 'dualist', 'philosophic...       0
7386  ['mollo', 'was', 'surprised', 'by', 'the', 'su...       0
7387  ['in', 'the', 'end', ',', 'president', 'truman...       0
7388  ['the', 'previous', 'mayor', ',', 'bill', 'laf...       0

[7389 rows x 2 columns]

In [75]:
data = [(eval(x), y) for x, y in zip((dft_eng["document_plaintext_tokenized"]), dft_eng["labels"])]

test_data = [(eval(x), y) for x, y in zip((dft_eng["question_text_tokenized"]), dft_eng["labels"])]

label_to_ix = {0: 0, 1: 1}

In [59]:
test_data

[(['when', 'was', 'quantum', 'field', 'theory', 'developed', '?'], 1),
 (['who',
   'was',
   'the',
   'first',
   'nobel',
   'prize',
   'winner',
   'for',
   'literature',
   '?'],
  1),
 (['when', 'is', 'the', 'dialectical', 'method', 'used', '?'], 1),
 (['who', 'invented', 'hangul', '?'], 1),
 (['what', 'do', 'grasshoppers', 'eat', '?'], 1),
 (['how',
   'large',
   'is',
   'the',
   'kerman',
   'province',
   'of',
   'southeastern',
   'iran',
   '?'],
  1),
 (['when', 'was', 'guitar', 'hero', 'live', 'first', 'released', '?'], 1),
 (['when',
   'were',
   'bluebonnets',
   'named',
   'the',
   'state',
   'flower',
   'of',
   'texas',
   '?'],
  1),
 (['who', 'created', 'the', 'series', 'clannad', '?'], 1),
 (['when', 'was', 'the', 'uss', 'taylor', 'built', '?'], 1),
 (['what',
   "'s",
   'the',
   'difference',
   'between',
   'man-slaughter',
   'and',
   'homicide',
   '?'],
  1),
 (['when',
   'did',
   'dc',
   'comics',
   'first',
   'introduce',
   'the',
   'gu

In [67]:
# Function to map each word in the vocab to an unique integer
# Indexing the Bag of words vector
word_to_ix = {}
for sent, _ in data + test_data:
    for word in sent:
        if word not in word_to_ix:
            word_to_ix[word] = len(word_to_ix)
print(word_to_ix)

{'quantum': 0, 'field': 1, 'theory': 2, 'naturally': 3, 'began': 4, 'with': 5, 'the': 6, 'study': 7, 'of': 8, 'electromagnetic': 9, 'interactions': 10, ',': 11, 'as': 12, 'was': 13, 'only': 14, 'known': 15, 'classical': 16, '1920s.': 17, '[': 18, '8': 19, ']': 20, ':1': 21, 'nobel': 22, 'prize': 23, 'in': 24, 'literature': 25, '(': 26, 'swedish': 27, ':': 28, 'nobelpriset': 29, 'i': 30, 'litteratur': 31, ')': 32, 'is': 33, 'awarded': 34, 'annually': 35, 'by': 36, 'academy': 37, 'to': 38, 'authors': 39, 'for': 40, 'outstanding': 41, 'contributions': 42, 'literature.': 43, 'it': 44, 'one': 45, 'five': 46, 'prizes': 47, 'established': 48, '1895': 49, 'will': 50, 'alfred': 51, 'which': 52, 'are': 53, 'chemistry': 54, 'physics': 55, 'peace': 56, 'and': 57, 'physiology': 58, 'or': 59, 'medicine.': 60, '1': 61, 'dictated': 62, "'s": 63, 'award': 64, 'administered': 65, 'foundation': 66, 'a': 67, 'committee': 68, 'that': 69, 'consists': 70, 'members': 71, 'elected': 72, 'academy.': 73, '2': 74

In [68]:
VOCAB_SIZE = len(word_to_ix)
NUM_LABELS = 2

In [63]:
class BoWClassifier(nn.Module):

    def __init__(self, num_labels, vocab_size, num_hidden = 2):
        # Calls the init function of nn.Module. 
        super(BoWClassifier, self).__init__()

        # Define the parameters that you need.
        self.linear = nn.Linear(vocab_size, num_hidden)
        # non-linearity (here it is also a layer!)
        self.nonlinear = nn.ReLU()
        # final affine transformation
        self.final = nn.Linear(num_hidden, num_labels)

    def forward(self, bow_vec):
        # Pass the input through the linear layer,
        # then pass that through log_softmax.
        # Many non-linearities and other functions are in torch.nn.functional
        return self.final(self.nonlinear(self.linear(bow_vec)))

In [64]:
# Functions to create BoW vectors
def make_bow_vector(sentence, word_to_ix):
    vec = torch.zeros(len(word_to_ix))
    for word in sentence:
        vec[word_to_ix[word]] += 1
    return vec.view(1, -1)


def make_target(label, label_to_ix):
    return torch.LongTensor([label_to_ix[label]])

In [69]:
model = BoWClassifier(NUM_LABELS, VOCAB_SIZE)

# The first output below is A, the second is b.
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-1.5955e-03,  1.2961e-04, -1.9433e-03,  ...,  1.6687e-03,
         -2.4039e-03,  2.5324e-03],
        [-1.0587e-03,  3.3005e-03,  1.4455e-04,  ..., -1.4436e-03,
         -3.8863e-05, -3.5877e-03]], requires_grad=True)
Parameter containing:
tensor([-0.0026,  0.0020], requires_grad=True)
Parameter containing:
tensor([[ 0.3175, -0.5351],
        [-0.2993, -0.4200]], requires_grad=True)
Parameter containing:
tensor([-0.5064, -0.4710], requires_grad=True)


In [72]:
with torch.no_grad():
    for text, label in test_data:
        bow_vec = make_bow_vector(text, word_to_ix)
        log_probs = model(bow_vec)
        print(log_probs)

# Print the matrix column corresponding to "creo"
print(next(model.parameters())[:, word_to_ix["quantum"]])

tensor([[-0.5099, -0.4737]])
tensor([[-0.5088, -0.4729]])
tensor([[-0.5118, -0.4753]])
tensor([[-0.5122, -0.4756]])
tensor([[-0.5098, -0.4737]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5119, -0.4753]])
tensor([[-0.5094, -0.4733]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5046, -0.4726]])
tensor([[-0.5094, -0.4734]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5108, -0.4745]])
tensor([[-0.5109, -0.4746]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5052, -0.4734]])
tensor([[-0.5090, -0.4731]])
tensor([[-0.5095, -0.4734]])
tensor([[-0.5088, -0.4729]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5132, -0.4763]])
tensor([[-0.5117, -0.4752]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.50

tensor([[-0.5114, -0.4750]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5108, -0.4744]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5155, -0.4781]])
tensor([[-0.5155, -0.4781]])
tensor([[-0.5132, -0.4763]])
tensor([[-0.5069, -0.4714]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5098, -0.4737]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5121, -0.4755]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5095, -0.4734]])
tensor([[-0.5087, -0.4734]])
tensor([[-0.5072, -0.4716]])
tensor([[-0.5070, -0.4715]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5076, -0.4719]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5085, -0.4727]])
tensor([[-0.5141, -0.4771]])
tensor([[-0.5099, -0.4738]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5070, -0.4741]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5113, -0.4749]])
tensor([[-0.51

tensor([[-0.5084, -0.4726]])
tensor([[-0.5092, -0.4746]])
tensor([[-0.5129, -0.4761]])
tensor([[-0.5104, -0.4741]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5152, -0.4779]])
tensor([[-0.5076, -0.4719]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5095, -0.4734]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5070, -0.4715]])
tensor([[-0.5080, -0.4730]])
tensor([[-0.5111, -0.4760]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5066, -0.4712]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5113, -0.4749]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5093, -0.4732]])
tensor([[-0.5070, -0.4715]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5111, -0.4747]])
tensor([[-0.50

tensor([[-0.5095, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5067, -0.4713]])
tensor([[-0.5127, -0.4760]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5107, -0.4743]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5090, -0.4731]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5111, -0.4746]])
tensor([[-0.5117, -0.4751]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5088, -0.4729]])
tensor([[-0.5122, -0.4755]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5076, -0.4719]])
tensor([[-0.5116, -0.4751]])
tensor([[-0.5126, -0.4763]])
tensor([[-0.5098, -0.4737]])
tensor([[-0.5071, -0.4716]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5057, -0.4716]])
tensor([[-0.5100, -0.4738]])
tensor([[-0.5127, -0.4760]])
tensor([[-0.5086, -0.4727]])
tensor([[-0.5072, -0.4717]])
tensor([[-0.5116, -0.4751]])
tensor([[-0.5147, -0.4775]])
tensor([[-0.50

tensor([[-0.5064, -0.4710]])
tensor([[-0.5086, -0.4727]])
tensor([[-0.5100, -0.4738]])
tensor([[-0.5103, -0.4740]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5099, -0.4737]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5098, -0.4736]])
tensor([[-0.5091, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5149, -0.4777]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5122, -0.4763]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5094, -0.4734]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5079, -0.4722]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5076, -0.4720]])
tensor([[-0.5113, -0.4748]])
tensor([[-0.5143, -0.4772]])
tensor([[-0.5074, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5137, -0.4768]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5093, -0.4762]])
tensor([[-0.50

tensor([[-0.5096, -0.4735]])
tensor([[-0.5127, -0.4759]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5085, -0.4735]])
tensor([[-0.5117, -0.4752]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5122, -0.4755]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5069, -0.4714]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5070, -0.4726]])
tensor([[-0.5089, -0.4730]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5076, -0.4720]])
tensor([[-0.5089, -0.4729]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5131, -0.4763]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5103, -0.4740]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5062, -0.4711]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5100, -0.4738]])
tensor([[-0.5086, -0.4748]])
tensor([[-0.5076, -0.4719]])
tensor([[-0.50

tensor([[-0.5080, -0.4722]])
tensor([[-0.5095, -0.4747]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5078, -0.4753]])
tensor([[-0.5080, -0.4723]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5089, -0.4741]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5077, -0.4721]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5101, -0.4747]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5080, -0.4723]])
tensor([[-0.5077, -0.4721]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5086, -0.4728]])
tensor([[-0.5132, -0.4763]])
tensor([[-0.5086, -0.4728]])
tensor([[-0.5089, -0.4758]])
tensor([[-0.5113, -0.4749]])
tensor([[-0.50

tensor([[-0.5088, -0.4728]])
tensor([[-0.5087, -0.4728]])
tensor([[-0.5066, -0.4712]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5125, -0.4758]])
tensor([[-0.5172, -0.4794]])
tensor([[-0.5113, -0.4749]])
tensor([[-0.5072, -0.4716]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5128, -0.4761]])
tensor([[-0.5087, -0.4728]])
tensor([[-0.5085, -0.4727]])
tensor([[-0.5086, -0.4727]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5133, -0.4764]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5080, -0.4723]])
tensor([[-0.5116, -0.4751]])
tensor([[-0.5079, -0.4721]])
tensor([[-0.5055, -0.4729]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5080, -0.4723]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5070, -0.4717]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5096, -0.4757]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.50

tensor([[-0.5077, -0.4721]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5073, -0.4726]])
tensor([[-0.5070, -0.4714]])
tensor([[-0.5065, -0.4710]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5053, -0.4720]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5111, -0.4747]])
tensor([[-0.5099, -0.4738]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5120, -0.4754]])
tensor([[-0.5066, -0.4712]])
tensor([[-0.5127, -0.4760]])
tensor([[-0.5126, -0.4759]])
tensor([[-0.5075, -0.4739]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5104, -0.4741]])
tensor([[-0.5122, -0.4755]])
tensor([[-0.5096, -0.4745]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5118, -0.4753]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.51

tensor([[-0.5090, -0.4730]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5081, -0.4723]])
tensor([[-0.5148, -0.4776]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5142, -0.4771]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5149, -0.4777]])
tensor([[-0.5103, -0.4741]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5066, -0.4711]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5098, -0.4737]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5086, -0.4727]])
tensor([[-0.5119, -0.4753]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5067, -0.4716]])
tensor([[-0.5134, -0.4765]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5090, -0.4731]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5094, -0.4733]])
tensor([[-0.5087, -0.4728]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5113, -0.4748]])
tensor([[-0.5094, -0.4733]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5081, -0.4756]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.51

tensor([[-0.5064, -0.4710]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5103, -0.4740]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5091, -0.4738]])
tensor([[-0.5063, -0.4712]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5137, -0.4767]])
tensor([[-0.5091, -0.4742]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5099, -0.4744]])
tensor([[-0.5103, -0.4740]])
tensor([[-0.5088, -0.4728]])
tensor([[-0.5068, -0.4718]])
tensor([[-0.5070, -0.4714]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5100, -0.4739]])
tensor([[-0.5116, -0.4751]])
tensor([[-0.5116, -0.4751]])
tensor([[-0.5098, -0.4736]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5069, -0.4734]])
tensor([[-0.5095, -0.4734]])
tensor([[-0.5090, -0.4744]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.50

tensor([[-0.5072, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5107, -0.4754]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5126, -0.4758]])
tensor([[-0.5079, -0.4735]])
tensor([[-0.5099, -0.4738]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5084, -0.4753]])
tensor([[-0.5100, -0.4738]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5125, -0.4758]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5067, -0.4713]])
tensor([[-0.5060, -0.4713]])
tensor([[-0.5114, -0.4750]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5108, -0.4744]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5155, -0.4781]])
tensor([[-0.5155, -0.4781]])
tensor([[-0.5132, -0.4763]])
tensor([[-0.5069, -0.4714]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.50

tensor([[-0.5143, -0.4772]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5065, -0.4710]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5087, -0.4728]])
tensor([[-0.5081, -0.4724]])
tensor([[-0.5098, -0.4737]])
tensor([[-0.5087, -0.4728]])
tensor([[-0.5136, -0.4767]])
tensor([[-0.5073, -0.4725]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5112, -0.4748]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5122, -0.4755]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5132, -0.4763]])
tensor([[-0.5118, -0.4752]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5123, -0.4756]])
tensor([[-0.5111, -0.4747]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5066, -0.4711]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5088, -0.4729]])
tensor([[-0.50

tensor([[-0.5096, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5125, -0.4758]])
tensor([[-0.5117, -0.4752]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5081, -0.4724]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5157, -0.4783]])
tensor([[-0.5084, -0.4730]])
tensor([[-0.5135, -0.4765]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5112, -0.4752]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5099, -0.4738]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5099, -0.4737]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5070, -0.4715]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5119, -0.4753]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5100, -0.4753]])
tensor([[-0.51

tensor([[-0.5103, -0.4741]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5118, -0.4753]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5104, -0.4741]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5079, -0.4728]])
tensor([[-0.5079, -0.4722]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5085, -0.4726]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5073, -0.4737]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5162, -0.4787]])
tensor([[-0.5072, -0.4738]])
tensor([[-0.5138, -0.4768]])
tensor([[-0.5104, -0.4741]])
tensor([[-0.5133, -0.4764]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5058, -0.4733]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.50

tensor([[-0.5139, -0.4769]])
tensor([[-0.5089, -0.4730]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5069, -0.4714]])
tensor([[-0.5108, -0.4745]])
tensor([[-0.5067, -0.4712]])
tensor([[-0.5081, -0.4723]])
tensor([[-0.5116, -0.4750]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5129, -0.4761]])
tensor([[-0.5090, -0.4731]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5072, -0.4716]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5093, -0.4741]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5068, -0.4720]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5084, -0.4726]])
tensor([[-0.5099, -0.4738]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5105, -0.4742]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5090, -0.4730]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5070, -0.4714]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5134, -0.4765]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5112, -0.4748]])
tensor([[-0.51

tensor([[-0.5064, -0.4710]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5076, -0.4720]])
tensor([[-0.5071, -0.4715]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5068, -0.4713]])
tensor([[-0.5055, -0.4718]])
tensor([[-0.5107, -0.4744]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5101, -0.4739]])
tensor([[-0.5082, -0.4738]])
tensor([[-0.5113, -0.4748]])
tensor([[-0.5131, -0.4763]])
tensor([[-0.5085, -0.4727]])
tensor([[-0.5119, -0.4753]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5163, -0.4788]])
tensor([[-0.5078, -0.4721]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5080, -0.4722]])
tensor([[-0.5121, -0.4755]])
tensor([[-0.5159, -0.4785]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5070, -0.4715]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.50

tensor([[-0.5073, -0.4741]])
tensor([[-0.5072, -0.4716]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5057, -0.4715]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5070, -0.4714]])
tensor([[-0.5092, -0.4734]])
tensor([[-0.5079, -0.4722]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5102, -0.4740]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5094, -0.4739]])
tensor([[-0.5135, -0.4766]])
tensor([[-0.5100, -0.4739]])
tensor([[-0.5095, -0.4734]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5112, -0.4748]])
tensor([[-0.5066, -0.4712]])
tensor([[-0.5134, -0.4765]])
tensor([[-0.5084, -0.4725]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5118, -0.4752]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5073, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5060, -0.4734]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5118, -0.4752]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5116, -0.4750]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5079, -0.4722]])
tensor([[-0.50

tensor([[-0.5095, -0.4734]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5068, -0.4721]])
tensor([[-0.5109, -0.4745]])
tensor([[-0.5091, -0.4731]])
tensor([[-0.5074, -0.4726]])
tensor([[-0.5088, -0.4728]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5128, -0.4760]])
tensor([[-0.5088, -0.4729]])
tensor([[-0.5115, -0.4750]])
tensor([[-0.5124, -0.4757]])
tensor([[-0.5092, -0.4732]])
tensor([[-0.5096, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5074, -0.4718]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5065, -0.4711]])
tensor([[-0.5070, -0.4727]])
tensor([[-0.5139, -0.4769]])
tensor([[-0.5065, -0.4735]])
tensor([[-0.5076, -0.4719]])
tensor([[-0.5106, -0.4743]])
tensor([[-0.5113, -0.4748]])
tensor([[-0.5055, -0.4717]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5108, -0.4744]])
tensor([[-0.5075, -0.4719]])
tensor([[-0.5095, -0.4735]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5069, -0.4714]])
tensor([[-0.5113, -0.4748]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.50

tensor([[-0.5107, -0.4744]])
tensor([[-0.5130, -0.4761]])
tensor([[-0.5069, -0.4720]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5077, -0.4720]])
tensor([[-0.5052, -0.4721]])
tensor([[-0.5143, -0.4772]])
tensor([[-0.5090, -0.4731]])
tensor([[-0.5085, -0.4726]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5083, -0.4725]])
tensor([[-0.5114, -0.4749]])
tensor([[-0.5097, -0.4736]])
tensor([[-0.5139, -0.4769]])
tensor([[-0.5064, -0.4710]])
tensor([[-0.5075, -0.4718]])
tensor([[-0.5099, -0.4737]])
tensor([[-0.5065, -0.4713]])
tensor([[-0.5139, -0.4769]])
tensor([[-0.5104, -0.4741]])
tensor([[-0.5089, -0.4729]])
tensor([[-0.5112, -0.4747]])
tensor([[-0.5136, -0.4766]])
tensor([[-0.5113, -0.4749]])
tensor([[-0.5112, -0.4747]])
tensor([[-0.5093, -0.4733]])
tensor([[-0.5110, -0.4746]])
tensor([[-0.5093, -0.4732]])
tensor([[-0.5118, -0.4756]])
tensor([[-0.5082, -0.4724]])
tensor([[-0.5066, -0.4712]])
tensor([[-0.5112, -0.4747]])
tensor([[-0.50

In [73]:
loss_function = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [77]:
for epoch in range(10):
    for instance, label in data:
        # Step 1. Remember that PyTorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()

        # Step 2. Make our BOW vector and also we must wrap the target in a
        # Tensor as an integer. For example, if the target is SPANISH, then
        # we wrap the integer 0. The loss function then knows that the 0th
        # element of the log probabilities is the log probability
        # corresponding to SPANISH
        bow_vec = make_bow_vector(instance, word_to_ix)
        target = make_target(label, label_to_ix)

        # Step 3. Run our forward pass.
        log_probs = model(bow_vec)

        # Step 4. Compute the loss, gradients, and update the parameters by
        # calling optimizer.step()
        loss = loss_function(log_probs, target)
        loss.backward()
        optimizer.step()

In [78]:
with torch.no_grad():
    for instance, label in test_data:
        bow_vec = make_bow_vector(instance, word_to_ix)
        log_probs = model(bow_vec)
        print(log_probs)

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8051, -3.7821]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8052, -3.7823]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8049, -3.7817]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7823]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8051, -3.7820]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8048, -3.7815]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8052, -3.7823]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8052, -3.7823]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.8053, -3.7824]])
tensor([[ 2.80

In [ ]:
print(next(model.parameters())[:, word_to_ix["creo"]])