In [ ]:
import pandas as pd
import numpy as np
import random
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import torch
from torch.utils.data import Dataset, DataLoader
from typing import List, Tuple
import gensim.downloader
from torch.optim import Adam
from tqdm import tqdm_notebook as tqdm
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import pickle
from torch import nn

In [ ]:
!git clone https://github.com/hrobjarturh/nlptasks.git

fatal: destination path 'nlptasks' already exists and is not an empty directory.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd nlptasks

/content/nlptasks


In [ ]:
!pip install transformers
!pip install datasets


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
from datasets import load_dataset
from transformers import AutoTokenizer
import math 
import torch

device = torch.device("cpu")
if torch.cuda.is_available():
 device = torch.device("cuda")
device

device(type='cuda')

In [ ]:
#Load data
dataset = load_dataset("copenlu/answerable_tydiqa")
dataset

  0%|          | 0/2 [00:00<?, ?it/s]

DatasetDict({
    validation: Dataset({
        features: ['question_text', 'document_title', 'language', 'annotations', 'document_plaintext', 'document_url'],
        num_rows: 13325
    })
    train: Dataset({
        features: ['question_text', 'document_title', 'language', 'annotations', 'document_plaintext', 'document_url'],
        num_rows: 116067
    })
})

In [ ]:
#split data 
train_set = dataset["train"]
validation_set = dataset["validation"]

train_set = train_set.to_pandas()
validation_set = validation_set.to_pandas()
validation_set

question_text  \
0                                     อยุธยามีกี่อำเภอ ?   
1      كم عدد مرات فوز الأوروغواي ببطولة كاس العالم ل...   
2                 Siapakah yang menemuka benua Amerika ?   
3                                     化学兵器禁止条約はどこで採択された？   
4      ใครเป็นผู้ก่อการ ใน เหตุโจมตีในนอร์เวย์ พ.ศ. 2...   
...                                                  ...   
13320                              월드컵이 처음 개최된 나라는 어디인가?   
13321      Berapakah berat Ikan pari manta yag terbesar?   
13322  Когда впервые начали применять компьютерную гр...   
13323     หม่อมราชวงศ์สุขุมพันธุ์ บริพัตร เกิดเมื่อไหร่?   
13324                   ماهى أول مؤلفة لي ج. ك. رولينغ ؟   

                        document_title    language  \
0               จังหวัดพระนครศรีอยุธยา        thai   
1             قائمة نهائيات كأس العالم      arabic   
2                 Kristoforus Kolumbus  indonesian   
3                             化学兵器禁止条約    japanese   
4        เหตุโจมตีในนอร์เวย์ พ.ศ. 2554        thai   
...                                ...         ...   
13320                         FIFA 월드컵      korean   
13321                  Ikan pari manta  indonesian   
13322                    CGI (графика)     russian   
13323  หม่อมราชวงศ์สุขุมพันธุ์ บริพัตร        thai   
13324                     ج. ك. رولينغ      arabic   

                                             annotations  \
0          {'answer_start': [42], 'answer_text': ['16']}   
1      {'answer_start': [394], 'answer_text': ['بطولت...   
2      {'answer_start': [193], 'answer_text': ['orang...   
3          {'answer_start': [11], 'answer_text': ['パリ']}   
4      {'answer_start': [400], 'answer_text': ['แอนเด...   
...                                                  ...   
13320        {'answer_start': [-1], 'answer_text': ['']}   
13321        {'answer_start': [-1], 'answer_text': ['']}   
13322        {'answer_start': [-1], 'answer_text': ['']}   
13323        {'answer_start': [-1], 'answer_text': ['']}   
13324        {'answer_start': [-1], 'answer_text': ['']}   

                                      document_plaintext  \
0      \nปัจจุบันจังหวัดพระนครศรีอยุธยาประกอบด้วย 16 ...   
1      أقيمت البطولة 21 مرة، شارك في النهائيات 78 دول...   
2      Kolumbus bukanlah orang pertama yang tiba di A...   
3      1993年1月13日にパリにおいて署名がなされ、1997年4月29日に発効した[1]。実効的...   
4      เหตุโจมตีครั้งที่สองนั้นเกิดขึ้นในราวสองชั่วโม...   
...                                                  ...   
13320  브라질의 펠레는 FIFA 월드컵에 출전한 모든 선수들 중 최고로 월드컵 기록이 좋은...   
13321  Ciri khas manta adalah sepasang "tanduk" di de...   
13322  Созданием движущихся изображений занимается ко...   
13323  ลำดับหม่อมราชวงศ์สุขุมพันธุ์ บริพัตร\n\nพระบาท...   
13324  وبين الحين والآخر، تبدي رولينغ تناقضًا في أرآئ...   

                                            document_url  
0      https://th.wikipedia.org/wiki/%E0%B8%88%E0%B8%...  
1      https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D8%...  
2      https://id.wikipedia.org/wiki/Kristoforus%20Ko...  
3      https://ja.wikipedia.org/wiki/%E5%8C%96%E5%AD%...  
4      https://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%...  
...                                                  ...  
13320  https://ko.wikipedia.org/wiki/FIFA%20%EC%9B%94...  
13321  https://id.wikipedia.org/wiki/Ikan%20pari%20manta  
13322  https://ru.wikipedia.org/wiki/CGI%20%28%D0%B3%...  
13323  https://th.wikipedia.org/wiki/%E0%B8%AB%E0%B8%...  
13324  https://ar.wikipedia.org/wiki/%D8%AC.%20%D9%83...  

[13325 rows x 6 columns]

In [ ]:
chosen_language = ['english', 'japanese', 'finnish']

train_set = train_set[train_set['language'].isin(chosen_language)]
validation_set = validation_set[validation_set['language'].isin(chosen_language)]

validation_set

question_text  \
3                                     化学兵器禁止条約はどこで採択された？   
9                                オリヴィア・デ・ハヴィランドが生まれたのはいつ   
11                         Kauanko lasia on valmistettu?   
14                                Mikä on Ponzi-huijaus?   
20                Mikä oli Napoleonin sotien lopputulos?   
...                                                  ...   
13305      What is the most common first word by babies?   
13307                  Kuinka kauan valtiopäivät kestää?   
13315                                アイスランド共和国の首都はどこですか？   
13317                Milloin käytiin Persianlahden sota?   
13319  When did the Bundaberg Central State School be...   

                       document_title  language  \
3                            化学兵器禁止条約  japanese   
9                      オリヴィア・デ・ハヴィランド  japanese   
11                               Lasi   finnish   
14                      Ponzi-huijaus   finnish   
20                   Napoleonin sodat   finnish   
...                               ...       ...   
13305          Vocabulary development   english   
13307             Suomen valtiopäivät   finnish   
13315                          アイスランド  japanese   
13317              Persianlahden sota   finnish   
13319  Bundaberg Central State School   english   

                                             annotations  \
3          {'answer_start': [11], 'answer_text': ['パリ']}   
9      {'answer_start': [46], 'answer_text': ['1916年7...   
11     {'answer_start': [160], 'answer_text': ['noin ...   
14     {'answer_start': [39], 'answer_text': ['pyrami...   
20     {'answer_start': [15], 'answer_text': ['Ranska...   
...                                                  ...   
13305        {'answer_start': [-1], 'answer_text': ['']}   
13307        {'answer_start': [-1], 'answer_text': ['']}   
13315        {'answer_start': [-1], 'answer_text': ['']}   
13317        {'answer_start': [-1], 'answer_text': ['']}   
13319        {'answer_start': [-1], 'answer_text': ['']}   

                                      document_plaintext  \
3      1993年1月13日にパリにおいて署名がなされ、1997年4月29日に発効した[1]。実効的...   
9      \nオリヴィア・デ・ハヴィランド（Dame Olivia De Havilland, DBE...   
11     Vanhin tunnettu lasilaatu on alkali­kalkki­las...   
14     Ponzi-huijaus eli Ponzi-järjestelmä on pyramid...   
20     Sotien jälkeen Ranska alistettiin kovilla rauh...   
...                                                  ...   
13305  Social pragmatic theories, also in contrast to...   
13307  \nEnnen vuotta 1906 kokoontuivat säätyvaltiopä...   
13315  こうした危機を乗り切るため、アイスランド中央銀行は8日にロシアから40億ユーロの緊急融資を受...   
13317  Ilmaiskuilla oli erityisen tuhoisa vaikutus Ir...   
13319  By the 1880s the school site had become valuab...   

                                            document_url  
3      https://ja.wikipedia.org/wiki/%E5%8C%96%E5%AD%...  
9      https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%...  
11                    https://fi.wikipedia.org/wiki/Lasi  
14           https://fi.wikipedia.org/wiki/Ponzi-huijaus  
20      https://fi.wikipedia.org/wiki/Napoleonin%20sodat  
...                                                  ...  
13305  https://en.wikipedia.org/wiki/Vocabulary%20dev...  
13307  https://fi.wikipedia.org/wiki/Suomen%20valtiop...  
13315  https://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%...  
13317  https://fi.wikipedia.org/wiki/Persianlahden%20...  
13319  https://en.wikipedia.org/wiki/Bundaberg%20Cent...  

[3712 rows x 6 columns]

In [ ]:
def get_answerability(annotations):
    answerable = []
    for annot in annotations:
        if -1 in annot['answer_start']:
            answerable.append(0)
        else:
            answerable.append(1)
    return answerable

train_set['answerable'] = get_answerability(train_set['annotations'].tolist())
validation_set['answerable'] = get_answerability(validation_set['annotations'].tolist())

train_set.columns

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


Index(['question_text', 'document_title', 'language', 'annotations',
       'document_plaintext', 'document_url', 'answerable'],
      dtype='object')

In [ ]:
from datasets import DatasetDict, Dataset

def question_parag_combine(questions, paragraphs):
    """
    This function combines the questions and paragraphs into a single text
    Args:
        questions: list of questions
        paragraphs: list of paragraphs
    Returns:
        list of combined questions and paragraphs
    """
    training_data = []
    for index in range(len(questions)):
        training_data += [questions[index] + "\n" + paragraphs[index]]
        
    return training_data

def make_df(train_set, validation_set):

  d_q = train_set['question_text'].tolist()
  d_p = train_set['document_plaintext'].tolist()
  training_data = question_parag_combine(d_q,d_p)
  training_labels = train_set['answerable'].tolist()

  d_q = validation_set['question_text'].tolist()
  d_p = validation_set['document_plaintext'].tolist()
  validation_data = question_parag_combine(d_q,d_p)
  validation_labels = validation_set['answerable'].tolist()



  data_set = {}
  sets = [['train',training_data, training_labels], ['val', validation_data, validation_labels]]
  for meta in sets:
      data_set[meta[0]] = {}
      data_set[meta[0]]['text'] = []
      data_set[meta[0]]['labels'] = []
      
      for ind, text in enumerate(meta[1]):
          data_set[meta[0]]['text'].append(text)
          data_set[meta[0]]['labels'].append(meta[2][ind])

          

          
  data_set = DatasetDict({'train':Dataset.from_dict(data_set['train']),
                          'valid':Dataset.from_dict(data_set['val'])\
                        })
  return data_set

data_set = make_df(train_set, validation_set)
data_set

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 29868
    })
    valid: Dataset({
        features: ['text', 'labels'],
        num_rows: 3712
    })
})

In [ ]:
from transformers import XLMRobertaTokenizer, XLMRobertaForCausalLM, XLMRobertaConfig, XLMTokenizer, XLMConfig, XLMModel

tokenizer = XLMRobertaTokenizer.from_pretrained("roberta-base")
#config = XLMRobertaConfig.from_pretrained("xlm-roberta-base")
#config.is_decoder = True
#model = XLMRobertaForCausalLM.from_pretrained("roberta-base")

# Initializing a XLM configuration
#configuration = XLMConfig(causal = True)


OSError: ignored

In [ ]:
from transformers import XLMRobertaTokenizer, XLMRobertaForCausalLM, XLMRobertaConfig
import torch
!pip install SentencePiece

tokenizer = XLMRobertaTokenizer.from_pretrained("AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru")

model = XLMRobertaForCausalLM.from_pretrained("AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru")


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/516 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/781 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

If you want to use `XLMRobertaLMHeadModel` as a standalone, add `is_decoder=True.`
Some weights of the model checkpoint at AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru were not used when initializing XLMRobertaForCausalLM: ['qa_outputs.weight', 'qa_outputs.bias']
- This IS expected if you are initializing XLMRobertaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLMRobertaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of XLMRobertaForCausalLM were not initialized from the model checkpoint at AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru and are newly initialized: ['lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', '

In [ ]:
def question_parag_combine(questions, paragraphs):
    """
    This function combines the questions and paragraphs into a single text
    Args:
        questions: list of questions
        paragraphs: list of paragraphs
    Returns:
        list of combined questions and paragraphs
    """
    training_data = []
    for index in range(len(questions)):
        training_data += [questions[index] + "\n" + paragraphs[index]]
        
    return training_data

In [ ]:
block_size = 128

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

def group_texts(examples):
    # Concatenate all texts.
    keys = ['attention_mask', 'input_ids']
    concatenated_examples = {k: sum(examples[k], []) for k in keys}
    total_length = len(concatenated_examples[list(keys)[0]])
    # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
        # customize this part to your needs.
    total_length = (total_length // block_size) * block_size
    # Split by chunks of max_len.
    result = {
        k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    # this is needed as the used dataset is a subclass of ClassificationDataset, which requires label as a field...
    result["label"] = result["input_ids"].copy()
    result["labels"] = result["input_ids"].copy()
    return result

tokenized_datasets = data_set.map(tokenize_function, batched=True, batch_size=1000, num_proc=4, remove_columns=["text"])
tokenized_datasets_lm = tokenized_datasets.map(group_texts, batched=True, batch_size=1000, num_proc=4)
tokenized_datasets_lm = tokenized_datasets_lm.remove_columns(['label'])

#0:   0%|          | 0/8 [00:00<?, ?ba/s]

#1:   0%|          | 0/8 [00:00<?, ?ba/s]

#2:   0%|          | 0/8 [00:00<?, ?ba/s]

#3:   0%|          | 0/8 [00:00<?, ?ba/s]

#0:   0%|          | 0/1 [00:00<?, ?ba/s]

#1:   0%|          | 0/1 [00:00<?, ?ba/s]

#2:   0%|          | 0/1 [00:00<?, ?ba/s]

#3:   0%|          | 0/1 [00:00<?, ?ba/s]

#0:   0%|          | 0/8 [00:00<?, ?ba/s]

#1:   0%|          | 0/8 [00:00<?, ?ba/s]

#2:   0%|          | 0/8 [00:00<?, ?ba/s]

#3:   0%|          | 0/8 [00:00<?, ?ba/s]

#0:   0%|          | 0/1 [00:00<?, ?ba/s]

#1:   0%|          | 0/1 [00:00<?, ?ba/s]

#2:   0%|          | 0/1 [00:00<?, ?ba/s]

#3:   0%|          | 0/1 [00:00<?, ?ba/s]

In [ ]:
import datasets

#tokenized_datasets_lm.save_to_disk('tokenized_dataset')


In [ ]:
%pwd

'/content/nlptasks/data'

In [ ]:
data_set = datasets.load_from_disk('tokenized_dataset')

In [ ]:
from transformers import Trainer, TrainingArguments
#training
#model_name = model_checkpoint.split("/")[-1]
training_args = TrainingArguments(
    "test-clm",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    num_train_epochs=1,
    per_device_train_batch_size = 2
    #max_steps=300
)

In [ ]:
data_set

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 29868
    })
    valid: Dataset({
        features: ['text', 'labels'],
        num_rows: 3712
    })
})

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets_lm['train'].shuffle(seed=42).select(range(5000)),
    eval_dataset= tokenized_datasets_lm['valid'],
)

In [ ]:
eval_results = trainer.evaluate()


print(f"Perplexity: {math.exp(eval_results['eval_loss']):.2f}")

***** Running Evaluation *****
  Num examples = 14848
  Batch size = 8


Perplexity: 8987236108.55


In [ ]:
trainer.train()

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 5000
  Num Epochs = 1
  Instantaneous batch size per device = 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
  Total optimization steps = 2500
  Number of trainable parameters = 560142482


Saving model checkpoint to test-clm/checkpoint-500
Configuration saved in test-clm/checkpoint-500/config.json
Model weights saved in test-clm/checkpoint-500/pytorch_model.bin
Saving model checkpoint to test-clm/checkpoint-1000
Configuration saved in test-clm/checkpoint-1000/config.json
Model weights saved in test-clm/checkpoint-1000/pytorch_model.bin
Saving model checkpoint to test-clm/checkpoint-1500
Configuration saved in test-clm/checkpoint-1500/config.json
Model weights saved in test-clm/checkpoint-1500/pytorch_model.bin
Saving model checkpoint to test-clm/checkpoint-2000
Configuration saved in test-clm/checkpoint-2000/config.json
Model weights saved in test-clm/checkpoint-2000/pytorch_model.bin
Saving model checkpoint to test-clm/checkpoint-2500
Configuration saved in test-clm/checkpoint-2500/config.json
Model weights saved in test-clm/checkpoint-2500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 14848
  Batch size = 8




Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=2500, training_loss=1.1766483459472656, metrics={'train_runtime': 2274.6969, 'train_samples_per_second': 2.198, 'train_steps_per_second': 1.099, 'total_flos': 1165874204160000.0, 'train_loss': 1.1766483459472656, 'epoch': 1.0})

In [ ]:
eval_results = trainer.evaluate()


print(f"Perplexity: {math.exp(eval_results['eval_loss']):.2f}")


***** Running Evaluation *****
  Num examples = 14848
  Batch size = 8


Perplexity: 1.25


In [ ]:
eng_eval_results = eng_trainer.evaluate()
print(f"Perplexity: {math.exp(eng_eval_results['eval_loss']):.2f}")

***** Running Evaluation *****
  Num examples = 1107
  Batch size = 8


Perplexity: 48.74


In [ ]:
torch.save(model, '../models/multi_model.pth')

In [ ]:
model = torch.load('models/multi_model.pth',map_location ='cpu')

In [ ]:
# Export contextual representations:

def mean_pooling(model_output, attention_mask):
    # Mean Pooling - Take attention mask into account for correct averaging
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(model_output.size()).float()
    sum_embeddings = torch.sum(model_output * input_mask_expanded, 1)
    sum_mask = torch.clamp(input_mask_expanded.sum(1), min=1e-9)
    return sum_embeddings / sum_mask


In [ ]:
current_language = 'eng'
# import training data
#dft = pd.read_csv('data/dft_'+current_language+'.csv')
frames = [pd.read_csv('data/dft_eng.csv'), pd.read_csv('data/dft_jap.csv'), pd.read_csv('data/dft_fin.csv')]
dft = pd.concat(frames)
dft = dft.sample(frac=1)


# import validation data
frames = [pd.read_csv('data/dfv_eng.csv'), pd.read_csv('data/dfv_jap.csv'), pd.read_csv('data/dfv_fin.csv')]
dfv = pd.concat(frames)
dfv = dfv.sample(frac=1)

dfv

question_text  \
579   When did Australia separate from Britain?   
385  What is the origin of the word technology?   
413              What is the weak atomic force?   
241               Mikä on kalasääsken elinalue?   
643               When was Last Exile released?   
..                                          ...   
872                               マラウイ共和国の首都はどこ   
970            Milloin Iirin kieli on syntynyt?   
531    Why is the flight deck called a cockpit?   
891                          ユダヤ教の原典は何語で書かれている？   
540                                名古屋市電はいつ設立した   

                          document_title  language  \
579  Constitutional history of Australia   english   
385                           Technology   english   
413                     Weak interaction   english   
241                               Sääksi   finnish   
643                           Last Exile   english   
..                                   ...       ...   
872                                 マラウイ  japanese   
970                                 Iiri   finnish   
531                              Cockpit   english   
891                                 ユダヤ教  japanese   
540                                名古屋市電  japanese   

                                           annotations  \
579  {'answer_start': array([-1]), 'answer_text': a...   
385  {'answer_start': array([37]), 'answer_text': a...   
413  {'answer_start': array([84]), 'answer_text': a...   
241  {'answer_start': array([121]), 'answer_text': ...   
643  {'answer_start': array([-1]), 'answer_text': a...   
..                                                 ...   
872  {'answer_start': array([-1]), 'answer_text': a...   
970  {'answer_start': array([-1]), 'answer_text': a...   
531  {'answer_start': array([-1]), 'answer_text': a...   
891  {'answer_start': array([-1]), 'answer_text': a...   
540  {'answer_start': array([-1]), 'answer_text': a...   

                                    document_plaintext  \
579  Between 1855 and 1890, the six colonies indivi...   
385  Technology ("science of craft", from Greek τέχ...   
413  In particle physics, the weak interaction (the...   
241  Sääksi eli kalasääski[1], vanhemmalta nimeltää...   
643  Conceptual designs were created by Range Murat...   
..                                                 ...   
872               日本はマラウイを独立と同時に承認し、現在では相互に大使館を開設している。   
970  Adjektiivit seuraavat pääsanaansa ja noudattav...   
531  The flight management system/control unit may ...   
891  Rabbi Hayim Halevy Donin: "To Be a Jew: A Guid...   
540                     このほかにも、大分交通や秋保電気軌道に譲渡された単車がある。   

                                          document_url  \
579  https://en.wikipedia.org/wiki/Constitutional%2...   
385           https://en.wikipedia.org/wiki/Technology   
413   https://en.wikipedia.org/wiki/Weak%20interaction   
241     https://fi.wikipedia.org/wiki/S%C3%A4%C3%A4ksi   
643         https://en.wikipedia.org/wiki/Last%20Exile   
..                                                 ...   
872  https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%...   
970                 https://fi.wikipedia.org/wiki/Iiri   
531              https://en.wikipedia.org/wiki/Cockpit   
891  https://ja.wikipedia.org/wiki/%E3%83%A6%E3%83%...   
540  https://ja.wikipedia.org/wiki/%E5%90%8D%E5%8F%...   

                               question_text_tokenized  \
579  ['When', 'did', 'Australia', 'separate', 'from...   
385  ['What', 'is', 'the', 'origin', 'of', 'the', '...   
413  ['What', 'is', 'the', 'weak', 'atomic', 'force...   
241     ['Mikä', 'on', 'kalasääsken', 'elinalue', '?']   
643  ['When', 'was', 'Last', 'Exile', 'released', '?']   
..                                                 ...   
872          ['マラウイ', '共和', '国', 'の', '首都', 'は', 'どこ']   
970  ['Milloin', 'Iirin', 'kieli', 'on', 'syntynyt'...   
531  ['Why', 'is', 'the', 'flight', 'deck', 'called...   
891  ['ユダヤ', '教', 'の', '原典', 'は', '何語', 'で', '書か', ...   
540           ['名古屋', '市電', 'は', 'いつ', '設立'

In [ ]:
seed = 5555
size_train = 5000
size_valid = 2000

In [ ]:
arange_dft = np.arange(len(dft))
np.random.seed(seed)
np.random.shuffle(arange_dft)

dft = dft.iloc[arange_dft]

train_df = dft.iloc[:size_train]
valid_df = dft.iloc[size_train:size_train+size_valid]
test_df = dfv

train_meta = train_df[['word_frequency_score','logres_pred']].values
valid_meta = valid_df[['word_frequency_score','logres_pred']].values
test_meta = test_df[['word_frequency_score','logres_pred']].values

In [ ]:
def create_batch(df, meta, model):
  combined = []
  que = df["question_text"].values
  text = df["document_plaintext"].values
  for index in range(len(df)):
    combined.append(str(que[index])+" "+str(text[index]))
  
  last_hidden = []
  for ind, row in enumerate(combined):
    encoded = tokenizer(combined[ind],
                        return_tensors='pt',truncation=True,max_length=64)
    encoded = {k:v.to(device) for k, v in encoded.items()}
    with torch.no_grad():
      model_output = model(**encoded, output_hidden_states=True, return_dict=True)
    pooled_output  = mean_pooling(model_output['hidden_states'][-1], encoded['attention_mask'])
    last_hidden.append(pooled_output)

    pooled_output = pooled_output.detach().to(device)


    

  text_lens = [len(i) for i in combined] # length of all doc lists

  return last_hidden, text_lens, df.label.values, meta
  

In [ ]:
train_dataset = create_batch(train_df, train_meta, model.to(device))
val_dataset = create_batch(valid_df, valid_meta, model.to(device))

test_dataset = create_batch(test_df,test_meta, model.to(device)) # rest of training for testing

In [ ]:
#torch.save(train_dataset, 'data/eng_multi_train_batch')
#torch.save(test_dataset, 'data/eng_multi_test_batch')
torch.save(val_dataset, 'data/eng_multi_valid_batch')

In [ ]:
train_dataset[0]

[tensor([[-0.1701, -0.8200, -0.5246,  ..., -0.5821, -0.1738, -0.8841]],
        device='cuda:0'),
 tensor([[ 0.1880, -0.8857, -0.3175,  ..., -0.0600, -0.3588, -0.4961]],
        device='cuda:0'),
 tensor([[ 0.3339, -0.9852, -0.4065,  ..., -0.2992, -0.2093, -0.5090]],
        device='cuda:0'),
 tensor([[ 0.0553, -0.6645, -0.4488,  ..., -0.3355, -0.3800, -0.5093]],
        device='cuda:0'),
 tensor([[ 0.1018, -0.9663, -0.4457,  ..., -0.2723, -0.2810, -0.5800]],
        device='cuda:0'),
 tensor([[-0.1783, -0.8581, -0.4586,  ..., -0.2737, -0.3082, -0.5573]],
        device='cuda:0'),
 tensor([[ 0.2905, -1.0619, -0.7384,  ..., -0.3975, -0.2108, -0.4956]],
        device='cuda:0'),
 tensor([[-0.1783, -0.7144, -0.4465,  ..., -0.6284, -0.0295, -1.0761]],
        device='cuda:0'),
 tensor([[ 0.3119, -1.0844, -0.3405,  ..., -0.2242, -0.2396, -0.6788]],
        device='cuda:0'),
 tensor([[-0.1408, -0.8597, -0.5713,  ..., -0.6703,  0.0139, -0.7822]],
        device='cuda:0'),
 tensor([[ 0.3720, -

In [ ]:
combined = []
que = dfv["question_text"].values
text = dfv["document_plaintext"].values
for index in range(len(dfv)):
  combined.append(str(que[index])+" "+str(text[index]))

In [ ]:
train_data = []
valid_data = []
test_data = []
for row in combined:
  encoded = eng_tokenizer(combined[0],
                      return_tensors='pt')
  encoded = {k:v.to(device) for k, v in encoded.items()}

  model_output = eng_model(**encoded, output_hidden_states=True, return_dict=True)

  mean_model_output = mean_pooling(model_output['hidden_states'][-1], encoded['attention_mask'])

In [ ]:
  encoded = eng_tokenizer('This is words',
                      return_tensors='pt')
  encoded = {k:v.to(device) for k, v in encoded.items()}

  model_output = model(**encoded, output_hidden_states=True, return_dict=True)

  mean_model_output = mean_pooling(model_output['hidden_states'][-1], encoded['attention_mask'])

In [ ]:
mean_model_output

tensor([[-7.6618e-02,  3.0584e-01, -7.7772e-01,  2.7464e-01, -1.3996e-01,
          1.3528e-01,  2.2021e+00,  5.5615e-01, -1.6915e-01, -2.3814e-02,
          1.4020e-02,  4.3055e-02, -1.5713e-01,  1.1371e-01,  1.3940e-01,
          6.8808e-02, -2.5337e-01, -2.2795e-01,  3.8142e-02,  1.0883e-01,
          1.0344e-01, -1.0245e-01,  2.9589e-01, -3.3583e-01, -1.4743e-01,
         -9.0522e-02, -2.9030e-01, -2.0552e-01,  1.0589e-02,  1.2487e-01,
          2.2613e-02, -5.8727e-02, -7.3387e-02, -8.8789e-02, -6.8163e-03,
          3.8037e-01,  3.2271e+01,  2.7284e-01, -5.3693e-02,  5.0226e-01,
         -3.0682e-02,  2.8502e-01,  2.3457e-02,  2.2691e-02, -3.2705e-01,
         -8.4868e-02, -1.0843e-01, -2.5657e-01, -4.2096e-02,  5.6631e-01,
         -1.4963e-01,  3.5003e-01, -1.1763e-01, -5.4871e-03, -1.1295e-01,
          5.0442e-01, -5.6427e-04, -2.7593e-01,  5.1326e-02, -1.5914e-01,
          3.8852e-02,  1.5863e-01,  1.3620e-01, -1.2790e-01, -1.2219e+00,
         -8.4525e-02, -9.8851e-02, -2.

In [ ]:
print(model_output.keys())
print(len(model_output['hidden_states'])) # contextual representations of separate words from each of the 6 layes
print(model_output['hidden_states'][-1].shape) # last layer with contextual representations (batch_size x num words x representation dim)

# Aggregate all the representations into one
mean_model_output2 = mean_pooling(model_output['hidden_states'][-1], encoded['attention_mask'])


odict_keys(['logits', 'past_key_values', 'hidden_states'])
7
torch.Size([1, 68, 768])


In [ ]:
eng_tokenizer(eng_set['train']['text'][100],
                    return_tensors='pt')

{'input_ids': tensor([[ 2061,   389,   262,  9539,   286, 18522,    30,   198,   464,   509,
          9116, 43400,    12, 38328,  2746,   318,  2968,   306,  1900,   355,
           262,  1936,  9539,   286, 18522,    11,   996,   517, 14351,    11,
           262,  2746,  1281, 15968,   257, 17085,   286,  7016,  2585,  5924,
           416,  5651,   453,  2801,  3871,   706, 13669,    13,   383,  1936,
          9539,   389, 16199, 13437,    25, 14425,    11,  8993,    11, 23189,
            11,  8862,   290, 13427,    13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}